### ISSUE TITLE
npm run dev运行到69% 就跑不下去了  一直在69

### ISSUE THREAD

**Issue by zhangfan6644777** [TerryBeanX2/Webpack-React-Router-Redux-ES6#1]

**Comment by TerryBeanX2** [comment]
有人说过这个问题，貌似就是显示的事儿，你在localhost:8888应该可以看到开发环境下的效果的。对于运行到69%有可能是全局环境下的某些包跟我电脑里的包版本不一致，也可能是运行dev-server时追参的问题。
ps：我更改了下参数，你可以更新一下试一试。
