### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by wulucxy** [TerryBeanX2/Webpack-React-Router-Redux-ES6#3]
启动就报错：
```
Error: ENOENT: no such file or directory, stat '/work/FE/Webpack-React-Router-Redux-ES6/react-t/index.html'
```

**Comment by TerryBeanX2** [comment]
我在2017.5.4那条更新记录里说过“本地开发调试请在config里切回hash路由，不然刷新会有问题”，请再好好看一下。
另外 就算你没有切回hash路由 启动报错了，访问localhost:8888还是会看得到首页的。

**Comment by wulucxy** [comment]
跟hash没关系啊，你看看报错信息
```
Error: ENOENT: no such file or directory, stat '/work/FE/Webpack-React-Router-Redux-ES6/react-t/index.html'
```
肯定是webpack报错了

**Comment by TerryBeanX2** [comment]
那不是webpack报错，是dev-server.js报的错，webpack编译是成功的，只有你在刷新页面的时候才有可能报这个错。首先我不知道你的是否知道hashHistroy和browserHistory的区别，我已经明确说了，本地调试模式，请切回hash路由，因为针对brwoserHistory我只在线上做过部署，服务器端代码在server.js里。而且，你说跟hash没关系，大概是你不了解两种路由方式的区别。切换hash路由的方法，在src/config里修改config就好了，我有注释的。为了防止你提的这种问题再发生，我已经把本地调试的代码也切回了hash路由，你不知道怎么修改的话可以更新下git，就不会报错了。我的代码不一定很健壮，但是不会让你走弯路走错路，请多动手多尝试，这个问题我不会再做解答了。
