### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by yulidai** [TerryBeanX2/Webpack-React-Router-Redux-ES6#4]
代码大郅都看懂了自己也照着写一个小东西

遇到的问题是：如果我在My页面下刷新下页面，TabBar无法获取该状态（当然拉，因为没有载入页面时立刻读取路由状态更新redux）   但是我在你的代码里好像也没找到相应的处理代码  然而却在刷新后可以更新状态到redux   请教下魔法在哪里  ^_^

**Comment by TerryBeanX2** [comment]
通过组件的props传递的，我在QQ里具体给你解答。。
