### ISSUE TITLE
现有的commonAction中的doFetch不适用于formData形式的图片上传

### ISSUE THREAD

**Issue by yulidai** [TerryBeanX2/Webpack-React-Router-Redux-ES6#5]
现有的commonAction中的doFetch不适用于formData形式的图片上传（原因是JSON.stringify和header的缘故）  大神觉得在commonAction中开放deFetch和doUpload两个口子是否优雅？

**Comment by TerryBeanX2** [comment]
我觉得formData形式的上传完全可以单开一个api，毕竟完全不是JSON格式的数据传输了。以前做jQ的项目时，正常的$.ajax和formData的上传都是分开的，所以说它们在我眼里从来就不应该放一起~
