### ISSUE TITLE
关于scroller的问题

### ISSUE THREAD

**Issue by kivenZhou** [TerryBeanX2/Webpack-React-Router-Redux-ES6#6]
你好，我是使用antd-mobile上面的Tabs标签写的4个分类，点击切换的时候将数据渲染到listview上面，因为listview是同一个，所以在一个栏目下面翻了好几页之后在切换另外一个栏目的时候，滚动条还是上一个栏目的高度，怎么可以做到点击下一个栏目的时候让antd-mobile的滚动到最上面呢？

**Comment by TerryBeanX2** [comment]
点击的时候 同时把 ScrollView 的 scrollTop = 0 应该就可以 至于怎么找到ScrollView 方法有很多 通过ref属性往下找也行，或者设置id然后document.getElementById也行 我的这个项目HomeList组件和common文件夹里的NavBar组件里都有关于滚动列表的获取方法
