### ISSUE TITLE
uc浏览器不支持

### ISSUE THREAD

**Issue by chenkang084** [TerryBeanX2/Webpack-React-Router-Redux-ES6#7]
最近在研究这个代码，发现在uc浏览器下面页面出不来。
还有就是，请问如何在pc上面调试手机浏览器。adb,weinre 貌似都不太好用，你有没有什么推荐的方法。谢谢

**Comment by TerryBeanX2** [comment]
@chenkang084 我用UC是可以出来的啊，你换个手机试试
PC上面调试我用过UC开发者版本，QQ我记得也有开发者版本，其实现在Chrome自带的模拟环境已经挺好了，我觉得可以满足开发需求，所以也就没再深究过在PC上调试手机浏览器

**Comment by chenkang084** [comment]
@TerryBeanX2  uc不可以的，最新版也不行。我用2台安卓机都试过，不行的，一直是圆圈转的。

**Comment by TerryBeanX2** [comment]
@chenkang084 那就不知道了，可能在安卓上的UC有问题吧，我在IOS上的没问题，这个Bug不解决啦，还需要调试很麻烦的，一般这种单页应用都是跑在微信公众号里的~
